# Generated by Django 3.2 on 2022-09-03 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeesalarydetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=30)),
                ('Emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Emp_no',),
            },
        ),
    ]
